# Generated by Django 4.2 on 2024-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='upload_date',
            new_name='date',
        ),
    ]
